spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: test
          uri: https://www.baidu.com
          predicates:
            - Query=uri, baidu
        - id: qq
          uri: https://www.qq.com
          predicates:
            - Query=uri,qq

  application:
    name: gulimall-gateway